apiVersion: v1
kind: Service
metadata:
  name: release-name-service
spec:
  selector:
    app: nginx
  type: {{ .Values.service.type }}
  ports: 
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
