apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./nginx-chart

commonLabels:
  test-label: ""

configMapGenerator:
- name: valuetest
  behavior: merge
  options:
    disableNameSuffixHash: true
  files:
  - values=values.yaml
