apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: fluxtest
resources:
- ./nginx-chart
configMapGenerator:
- name: valuetest
  behavior: create
  options:
    disableNameSuffixHash: true
  files:
  - values=values.yaml
